{
  "description": "Exception caught by widgets library",
  "type": "_FlutterErrorDetailsNode",
  "allowWrap": false,
  "valueId": "inspector-0",
  "properties": [
    {
      "description": "The following TypeErrorImpl was thrown building LayoutBuilder:",
      "type": "ErrorDescription",
      "showSeparator": false,
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "valueId": "inspector-1",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "info"
    },
    {
      "description": "Unexpected null value.",
      "type": "ErrorSummary",
      "showSeparator": false,
      "level": "summary",
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "valueId": "inspector-2",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "summary"
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    },
    {
      "description": "",
      "type": "DiagnosticsBlock",
      "name": "The relevant error-causing widget was",
      "style": "whitespace",
      "hasChildren": true,
      "allowWrap": false,
      "valueId": null,
      "properties": [],
      "children": [
        {
          "description": "HexagonOffsetGrid HexagonOffsetGrid:file:///E:/FlutterCosas/TF_SOM/TF_SOM/lib/grillaHexagonos.dart:60:40",
          "type": "ErrorDescription",
          "showSeparator": false,
          "showName": false,
          "style": "flat",
          "allowNameWrap": true,
          "valueId": "inspector-3",
          "properties": [],
          "children": [],
          "defaultValue": "null",
          "missingIfNull": false,
          "propertyType": "List<Object>",
          "defaultLevel": "info"
        }
      ]
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    },
    {
      "description": "",
      "type": "DiagnosticsStackTrace",
      "name": "When the exception was thrown, this was the stack",
      "style": "flat",
      "allowWrap": false,
      "valueId": "inspector-4",
      "properties": [
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 943:18  nullCheck",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter_application_1/grillaHexagonos.dart 69:73                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 257:61                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 572:46                generate",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 234:38                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 156:34                         [_crossAxis]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 233:30                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 572:46                generate",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 231:33                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 150:37                         [_mainAxis]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/hexagon/src/grid/hexagon_offset_grid.dart 230:18                         <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/layout_builder.dart 116:70                           layoutCallback",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/framework.dart 2835:11                               buildScope",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/layout_builder.dart 150:5                            [_layout]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2657:51                                <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 1071:7                                 [_enableMutationsToDirtySubtrees]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2657:7                                 invokeLayoutCallback",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/layout_builder.dart 225:7                            rebuildIfNecessary",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/layout_builder.dart 308:5                            performLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 1434:11                             performLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/shifted_box.dart 238:5                             performLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/layout_helper.dart 52:10                           layoutChild",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/flex.dart 808:43                                   [_computeSizes]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/flex.dart 903:32                                   performLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2546:7                                 layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/box.dart 2389:11                                   layout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 2385:7                                 [_layoutWithoutResize]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 1025:17                                flushLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/object.dart 1038:14                                flushLayout",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/binding.dart 591:5                                 drawFrame",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/widgets/binding.dart 986:13                                  drawFrame",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/rendering/binding.dart 457:5                                 [_handlePersistentFrameCallback]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/scheduler/binding.dart 1325:7                                [_invokeFrameCallback]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/scheduler/binding.dart 1255:9                                handleDrawFrame",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "packages/flutter/src/scheduler/binding.dart 1113:5                                [_handleDrawFrame]",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "lib/_engine/engine/platform_dispatcher.dart 1274:5                                invoke",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "lib/_engine/engine/platform_dispatcher.dart 248:5                                 invokeOnDrawFrame",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "lib/_engine/engine/initialization.dart 186:36                                     <fn>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        }
      ],
      "children": []
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    }
  ],
  "children": [],
  "errorsSinceReload": 0,
  "renderedErrorText": "══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building LayoutBuilder:
Unexpected null value.

The relevant error-causing widget was:
  HexagonOffsetGrid
  HexagonOffsetGrid:file:///E:/FlutterCosas/TF_SOM/TF_SOM/lib/grillaHexagonos.dart:60:40

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 943:18  nullCheck
packages/flutter_application_1/grillaHexagonos.dart 69:73                         <fn>
packages/hexagon/src/grid/hexagon_offset_grid.dart 257:61                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 572:46                generate
packages/hexagon/src/grid/hexagon_offset_grid.dart 234:38                         <fn>
packages/hexagon/src/grid/hexagon_offset_grid.dart 156:34                         [_crossAxis]
packages/hexagon/src/grid/hexagon_offset_grid.dart 233:30                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 572:46                generate
packages/hexagon/src/grid/hexagon_offset_grid.dart 231:33                         <fn>
packages/hexagon/src/grid/hexagon_offset_grid.dart 150:37                         [_mainAxis]
packages/hexagon/src/grid/hexagon_offset_grid.dart 230:18                         <fn>
packages/flutter/src/widgets/layout_builder.dart 116:70                           layoutCallback
packages/flutter/src/widgets/framework.dart 2835:11                               buildScope
packages/flutter/src/widgets/layout_builder.dart 150:5                            [_layout]
packages/flutter/src/rendering/object.dart 2657:51                                <fn>
packages/flutter/src/rendering/object.dart 1071:7                                 [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2657:7                                 invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 225:7                            rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 308:5                            performLayout
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/proxy_box.dart 1434:11                             performLayout
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/shifted_box.dart 238:5                             performLayout
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/layout_helper.dart 52:10                           layoutChild
packages/flutter/src/rendering/flex.dart 808:43                                   [_computeSizes]
packages/flutter/src/rendering/flex.dart 903:32                                   performLayout
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2546:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/flutter/src/rendering/proxy_box.dart 104:21                              <fn>
packages/flutter/src/rendering/object.dart 2385:7                                 [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 1025:17                                flushLayout
packages/flutter/src/rendering/object.dart 1038:14                                flushLayout
packages/flutter/src/rendering/binding.dart 591:5                                 drawFrame
packages/flutter/src/widgets/binding.dart 986:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 457:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1325:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1255:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1113:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1274:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 248:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 186:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall

════════════════════════════════════════════════════════════════════════════════════════════════════"
}